# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from jeopardy import Jeopardy

import json

filename = 'JeopardyFinal.json'
with open(filename) as f:
    questions = json.load(f)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.jeopardy = Jeopardy() # Instance of Jeopardy class
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080) #1047 , 854
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(150,400, 200, 200))
        self.photo.setText("")
        self.photo.setPixmap(QPixmap('/home/flyseddy/Coding/BTPJeopardy/Sean.JPG'))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")

        self.seanName = QtWidgets.QLabel(self.centralwidget)
        self.seanName.setGeometry(QtCore.QRect(140,200, 250, 200))
        self.seanName.setText("Jeopardy Champion/Host!\nSean Hansen")
        self.seanName.setAlignment(QtCore.Qt.AlignCenter)
        self.seanName.setObjectName("seanName")

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(500, 90, 800, 500)) #0, 40, 621, 391
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cat1_clue2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat1_clue2.sizePolicy().hasHeightForWidth())
        self.cat1_clue2.setSizePolicy(sizePolicy)
        self.cat1_clue2.setObjectName("cat1_clue2")
        self.gridLayout.addWidget(self.cat1_clue2, 2, 0, 1, 1)
        self.cat4_clue1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat4_clue1.sizePolicy().hasHeightForWidth())
        self.cat4_clue1.setSizePolicy(sizePolicy)
        self.cat4_clue1.setObjectName("cat4_clue1")
        self.gridLayout.addWidget(self.cat4_clue1, 1, 3, 1, 1)
        self.cat2_clue4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat2_clue4.sizePolicy().hasHeightForWidth())
        self.cat2_clue4.setSizePolicy(sizePolicy)
        self.cat2_clue4.setObjectName("cat2_clue4")
        self.gridLayout.addWidget(self.cat2_clue4, 4, 1, 1, 1)
        self.cat3_clue2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat3_clue2.sizePolicy().hasHeightForWidth())
        self.cat3_clue2.setSizePolicy(sizePolicy)
        self.cat3_clue2.setObjectName("cat3_clue2")
        self.gridLayout.addWidget(self.cat3_clue2, 2, 2, 1, 1)
        self.cat5_clue2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat5_clue2.sizePolicy().hasHeightForWidth())
        self.cat5_clue2.setSizePolicy(sizePolicy)
        self.cat5_clue2.setObjectName("cat5_clue2")
        self.gridLayout.addWidget(self.cat5_clue2, 2, 4, 1, 1)
        self.cat2_clue1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat2_clue1.sizePolicy().hasHeightForWidth())
        self.cat2_clue1.setSizePolicy(sizePolicy)
        self.cat2_clue1.setObjectName("cat2_clue1")
        self.gridLayout.addWidget(self.cat2_clue1, 1, 1, 1, 1)
        self.cat1_clue3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat1_clue3.sizePolicy().hasHeightForWidth())
        self.cat1_clue3.setSizePolicy(sizePolicy)
        self.cat1_clue3.setObjectName("cat1_clue3")
        self.gridLayout.addWidget(self.cat1_clue3, 3, 0, 1, 1)
        self.cat5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat5.sizePolicy().hasHeightForWidth())
        self.cat5.setSizePolicy(sizePolicy)
        self.cat5.setObjectName("cat5")
        self.gridLayout.addWidget(self.cat5, 0, 4, 1, 1)
        self.cat1_clue1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat1_clue1.sizePolicy().hasHeightForWidth())
        self.cat1_clue1.setSizePolicy(sizePolicy)
        self.cat1_clue1.setObjectName("cat1_clue1")
        self.gridLayout.addWidget(self.cat1_clue1, 1, 0, 1, 1)
        self.cat3_clue3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat3_clue3.sizePolicy().hasHeightForWidth())
        self.cat3_clue3.setSizePolicy(sizePolicy)
        self.cat3_clue3.setObjectName("cat3_clue3")
        self.gridLayout.addWidget(self.cat3_clue3, 3, 2, 1, 1)
        self.cat5_clue4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat5_clue4.sizePolicy().hasHeightForWidth())
        self.cat5_clue4.setSizePolicy(sizePolicy)
        self.cat5_clue4.setObjectName("cat5_clue4")
        self.gridLayout.addWidget(self.cat5_clue4, 4, 4, 1, 1)
        self.cat5_clue3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat5_clue3.sizePolicy().hasHeightForWidth())
        self.cat5_clue3.setSizePolicy(sizePolicy)
        self.cat5_clue3.setObjectName("cat5_clue3")
        self.gridLayout.addWidget(self.cat5_clue3, 3, 4, 1, 1)
        self.cat3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat3.sizePolicy().hasHeightForWidth())
        self.cat3.setSizePolicy(sizePolicy)
        self.cat3.setObjectName("cat3")
        self.gridLayout.addWidget(self.cat3, 0, 2, 1, 1)
        self.cat4_clue2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat4_clue2.sizePolicy().hasHeightForWidth())
        self.cat4_clue2.setSizePolicy(sizePolicy)
        self.cat4_clue2.setObjectName("cat4_clue2")
        self.gridLayout.addWidget(self.cat4_clue2, 2, 3, 1, 1)
        self.cat2_clue3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat2_clue3.sizePolicy().hasHeightForWidth())
        self.cat2_clue3.setSizePolicy(sizePolicy)
        self.cat2_clue3.setObjectName("cat2_clue3")
        self.gridLayout.addWidget(self.cat2_clue3, 3, 1, 1, 1)
        self.cat4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat4.sizePolicy().hasHeightForWidth())
        self.cat4.setSizePolicy(sizePolicy)
        self.cat4.setObjectName("cat4")
        self.gridLayout.addWidget(self.cat4, 0, 3, 1, 1)
        self.cat4_clue3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat4_clue3.sizePolicy().hasHeightForWidth())
        self.cat4_clue3.setSizePolicy(sizePolicy)
        self.cat4_clue3.setObjectName("cat4_clue3")
        self.gridLayout.addWidget(self.cat4_clue3, 3, 3, 1, 1)
        self.cat3_clue4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat3_clue4.sizePolicy().hasHeightForWidth())
        self.cat3_clue4.setSizePolicy(sizePolicy)
        self.cat3_clue4.setObjectName("cat3_clue4")
        self.gridLayout.addWidget(self.cat3_clue4, 4, 2, 1, 1)
        self.cat2_clue2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat2_clue2.sizePolicy().hasHeightForWidth())
        self.cat2_clue2.setSizePolicy(sizePolicy)
        self.cat2_clue2.setObjectName("cat2_clue2")
        self.gridLayout.addWidget(self.cat2_clue2, 2, 1, 1, 1)
        self.cat2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat2.sizePolicy().hasHeightForWidth())
        self.cat2.setSizePolicy(sizePolicy)
        self.cat2.setObjectName("cat2")
        self.gridLayout.addWidget(self.cat2, 0, 1, 1, 1)
        self.cat5_clue1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat5_clue1.sizePolicy().hasHeightForWidth())
        self.cat5_clue1.setSizePolicy(sizePolicy)
        self.cat5_clue1.setObjectName("cat5_clue1")
        self.gridLayout.addWidget(self.cat5_clue1, 1, 4, 1, 1)
        self.cat3_clue1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat3_clue1.sizePolicy().hasHeightForWidth())
        self.cat3_clue1.setSizePolicy(sizePolicy)
        self.cat3_clue1.setObjectName("cat3_clue1")
        self.gridLayout.addWidget(self.cat3_clue1, 1, 2, 1, 1)
        self.cat1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat1.sizePolicy().hasHeightForWidth())
        self.cat1.setSizePolicy(sizePolicy)
        self.cat1.setObjectName("cat1")
        self.gridLayout.addWidget(self.cat1, 0, 0, 1, 1)
        self.cat1_clue4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat1_clue4.sizePolicy().hasHeightForWidth())
        self.cat1_clue4.setSizePolicy(sizePolicy)
        self.cat1_clue4.setObjectName("cat1_clue4")
        self.gridLayout.addWidget(self.cat1_clue4, 4, 0, 1, 1)
        self.cat4_clue4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cat4_clue4.sizePolicy().hasHeightForWidth())
        self.cat4_clue4.setSizePolicy(sizePolicy)
        self.cat4_clue4.setObjectName("cat4_clue4")
        self.gridLayout.addWidget(self.cat4_clue4, 4, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(520, 20, 771, 50)) #21
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BTPLogo = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.BTPLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.BTPLogo.setObjectName("BTPLogo")
        self.horizontalLayout.addWidget(self.BTPLogo)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(600, 625, 621, 171)) # Revealed Question
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RevealedQuestionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.RevealedQuestionLabel.setGeometry(QtCore.QRect(250, 70, 67, 50))
        self.RevealedQuestionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RevealedQuestionLabel.setObjectName("RevealedQuestionLabel")
        self.RevealedQuestionLabel.setWordWrap(True)
        self.verticalLayout.addWidget(self.RevealedQuestionLabel)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(600, 750, 621, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.RevealedAnswerLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.RevealedAnswerLabel.setGeometry(QtCore.QRect(250, 60, 67, 17))
        self.RevealedAnswerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RevealedAnswerLabel.setObjectName("RevealedAnswerLabel")
        self.verticalLayout_3.addWidget(self.RevealedAnswerLabel)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1390, 100, 160, 88))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Team1Label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Team1Label.setObjectName("Team1Label")
        self.verticalLayout_5.addWidget(self.Team1Label)
        self.Team2Label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Team2Label.setObjectName("Team2Label")
        self.verticalLayout_5.addWidget(self.Team2Label)
        self.Team3Label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Team3Label.setObjectName("Team3Label")
        self.verticalLayout_5.addWidget(self.Team3Label)
        self.Team4Label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Team4Label.setObjectName("Team4Label")
        self.verticalLayout_5.addWidget(self.Team4Label)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1500, 100, 160, 88))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Team1Score = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Team1Score.setObjectName("Team1Score")
        self.verticalLayout_6.addWidget(self.Team1Score)
        self.Team2Score = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Team2Score.setObjectName("Team2Score")
        self.verticalLayout_6.addWidget(self.Team2Score)
        self.Team3Score = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Team3Score.setObjectName("Team3Score")
        self.verticalLayout_6.addWidget(self.Team3Score)
        self.Team4Score = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Team4Score.setObjectName("Team4Score")
        self.verticalLayout_6.addWidget(self.Team4Score)
        self.label_9 = QtWidgets.QLabel(self.centralwidget) # Score Label
        self.label_9.setGeometry(QtCore.QRect(1500, 70, 67, 17))
        self.label_9.setObjectName("label_9")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1400, 440, 351, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.WrongTeam2Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.WrongTeam2Button.setObjectName("WrongTeam2Button")
        self.gridLayout_3.addWidget(self.WrongTeam2Button, 1, 1, 1, 1)
        self.CorrectTeam2Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.CorrectTeam2Button.setObjectName("CorrectTeam2Button")
        self.gridLayout_3.addWidget(self.CorrectTeam2Button, 1, 0, 1, 1)
        self.WrongTeam3Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.WrongTeam3Button.setObjectName("WrongTeam3Button")
        self.gridLayout_3.addWidget(self.WrongTeam3Button, 2, 1, 1, 1)
        self.CorrectTeam3Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.CorrectTeam3Button.setObjectName("CorrectTeam3Button")
        self.gridLayout_3.addWidget(self.CorrectTeam3Button, 2, 0, 1, 1)
        self.CorrectTeam4Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.CorrectTeam4Button.setObjectName("CorrectTeam4Button")
        self.gridLayout_3.addWidget(self.CorrectTeam4Button, 3, 0, 1, 1)
        self.WrongTeam4Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.WrongTeam4Button.setObjectName("WrongTeam4Button")
        self.gridLayout_3.addWidget(self.WrongTeam4Button, 3, 1, 1, 1)
        self.WrongTeam1Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.WrongTeam1Button.setObjectName("WrongTeam1Button")
        self.gridLayout_3.addWidget(self.WrongTeam1Button, 0, 1, 1, 1)
        self.CorrectTeam1Button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.CorrectTeam1Button.setObjectName("CorrectTeam1Button")
        self.gridLayout_3.addWidget(self.CorrectTeam1Button, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1400, 407, 101, 20))
        self.label.setObjectName("label")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1400, 720, 160, 80)) # Display answer
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_3 = QtWidgets.QFrame(self.verticalLayoutWidget_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.DisplayAnswerButton = QtWidgets.QPushButton(self.frame_3)
        self.DisplayAnswerButton.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.DisplayAnswerButton.setObjectName("DisplayAnswerButton")
        self.verticalLayout_8.addWidget(self.frame_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1400, 680, 101, 21)) # Gameboard Label
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1400, 272, 160, 80))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.RoundLabel = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.RoundLabel.setObjectName("RoundLabel")
        self.verticalLayout_9.addWidget(self.RoundLabel)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1500, 270, 160, 80)) # Round number
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.RoundNumber = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.RoundNumber.setObjectName("RoundNumber")
        self.verticalLayout_10.addWidget(self.RoundNumber)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(1590, 720, 160, 80)) # Reset Game board and Next Round
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.resetButton.setObjectName("resetButton")
        self.nextRoundButton = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.nextRoundButton.setObjectName("nextRoundButton")
        self.verticalLayout_11.addWidget(self.resetButton)
        self.verticalLayout_11.addWidget(self.nextRoundButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Make categories not pressable
        self.cat1.setCheckable(False)
        self.cat2.setCheckable(False)
        self.cat3.setCheckable(False)
        self.cat4.setCheckable(False)
        self.cat5.setCheckable(False)

        # Cat Button actions
        self.cat1_clue1.clicked.connect(lambda: self.cat_click(0, self.cat1_clue1))
        self.cat1_clue2.clicked.connect(lambda: self.cat_click(1, self.cat1_clue2))
        self.cat1_clue3.clicked.connect(lambda: self.cat_click(2, self.cat1_clue3))
        self.cat1_clue4.clicked.connect(lambda: self.cat_click(3, self.cat1_clue4))
        self.cat2_clue1.clicked.connect(lambda: self.cat_click(4, self.cat2_clue1))
        self.cat2_clue2.clicked.connect(lambda: self.cat_click(5, self.cat2_clue2))
        self.cat2_clue3.clicked.connect(lambda: self.cat_click(6, self.cat2_clue3))
        self.cat2_clue4.clicked.connect(lambda: self.cat_click(7, self.cat2_clue4))
        self.cat3_clue1.clicked.connect(lambda: self.cat_click(8, self.cat3_clue1))
        self.cat3_clue2.clicked.connect(lambda: self.cat_click(9, self.cat3_clue2))
        self.cat3_clue3.clicked.connect(lambda: self.cat_click(10, self.cat3_clue3))
        self.cat3_clue4.clicked.connect(lambda: self.cat_click(11, self.cat3_clue4))
        self.cat4_clue1.clicked.connect(lambda: self.cat_click(12, self.cat4_clue1))
        self.cat4_clue2.clicked.connect(lambda: self.cat_click(13, self.cat4_clue2))
        self.cat4_clue3.clicked.connect(lambda: self.cat_click(14, self.cat4_clue3))
        self.cat4_clue4.clicked.connect(lambda: self.cat_click(15, self.cat4_clue4))
        self.cat5_clue1.clicked.connect(lambda: self.cat_click(16, self.cat5_clue1))
        self.cat5_clue2.clicked.connect(lambda: self.cat_click(17, self.cat5_clue2))
        self.cat5_clue3.clicked.connect(lambda: self.cat_click(18, self.cat5_clue3))
        self.cat5_clue4.clicked.connect(lambda: self.cat_click(19, self.cat5_clue4))

        # Display Answer
        self.DisplayAnswerButton.clicked.connect(lambda: self.display_answer_click())

        # Correct or Wrong
        self.CorrectTeam1Button.clicked.connect(lambda: self.correctTeam1())
        self.CorrectTeam2Button.clicked.connect(lambda: self.correctTeam2())
        self.CorrectTeam3Button.clicked.connect(lambda: self.correctTeam3())
        self.CorrectTeam4Button.clicked.connect(lambda: self.correctTeam4())

        self.WrongTeam1Button.clicked.connect(lambda: self.wrongTeam1())
        self.WrongTeam2Button.clicked.connect(lambda: self.wrongTeam2())
        self.WrongTeam3Button.clicked.connect(lambda: self.wrongTeam3())
        self.WrongTeam4Button.clicked.connect(lambda: self.wrongTeam4())

        # Reset Gameboard
        self.resetButton.clicked.connect(lambda: self.resetGameboard())

        # Next Round
        self.nextRoundButton.clicked.connect(lambda: self.nextRound())



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BTP Jeopardy!"))
        self.cat1_clue2.setText(_translate("MainWindow", "200"))
        self.cat4_clue1.setText(_translate("MainWindow", "100"))
        self.cat2_clue4.setText(_translate("MainWindow", "400"))
        self.cat3_clue2.setText(_translate("MainWindow", "200"))
        self.cat5_clue2.setText(_translate("MainWindow", "200"))
        self.cat2_clue1.setText(_translate("MainWindow", "100"))
        self.cat1_clue3.setText(_translate("MainWindow", "300"))
        self.cat5.setText(_translate("MainWindow", questions[16]['Category']))
        self.cat1_clue1.setText(_translate("MainWindow", "100"))
        self.cat3_clue3.setText(_translate("MainWindow", "300"))
        self.cat5_clue4.setText(_translate("MainWindow", "400"))
        self.cat5_clue3.setText(_translate("MainWindow", "300"))
        self.cat3.setText(_translate("MainWindow", questions[8]['Category']))
        self.cat4_clue2.setText(_translate("MainWindow", "200"))
        self.cat2_clue3.setText(_translate("MainWindow", "300"))
        self.cat4.setText(_translate("MainWindow", questions[12]['Category']))
        self.cat4_clue3.setText(_translate("MainWindow", "300"))
        self.cat3_clue4.setText(_translate("MainWindow", "400"))
        self.cat2_clue2.setText(_translate("MainWindow", "200"))
        self.cat2.setText(_translate("MainWindow", questions[4]['Category']))
        self.cat5_clue1.setText(_translate("MainWindow", "100"))
        self.cat3_clue1.setText(_translate("MainWindow", "100"))
        self.cat1.setText(_translate("MainWindow", questions[0]['Category']))
        self.cat1_clue4.setText(_translate("MainWindow", "400"))
        self.cat4_clue4.setText(_translate("MainWindow", "400"))
        self.BTPLogo.setText(_translate("MainWindow", "BTP Jeopardy!"))
        self.RevealedQuestionLabel.setText(_translate("MainWindow", "Question"))
        self.RevealedAnswerLabel.setText(_translate("MainWindow", "Answer"))
        self.Team1Label.setText(_translate("MainWindow", "Team 1"))
        self.Team2Label.setText(_translate("MainWindow", "Team 2"))
        self.Team3Label.setText(_translate("MainWindow", "Team 3"))
        self.Team4Label.setText(_translate("MainWindow", "Team 4"))
        self.Team1Score.setText(_translate("MainWindow", "0"))
        self.Team2Score.setText(_translate("MainWindow", "0"))
        self.Team3Score.setText(_translate("MainWindow", "0"))
        self.Team4Score.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Score"))
        self.WrongTeam2Button.setText(_translate("MainWindow", "Wrong Team 2"))
        self.CorrectTeam2Button.setText(_translate("MainWindow", "Correct Team 2"))
        self.WrongTeam3Button.setText(_translate("MainWindow", "Wrong Team 3"))
        self.CorrectTeam3Button.setText(_translate("MainWindow", "Correct Team 3"))
        self.CorrectTeam4Button.setText(_translate("MainWindow", "Correct Team 4"))
        self.WrongTeam4Button.setText(_translate("MainWindow", "Wrong Team 4"))
        self.WrongTeam1Button.setText(_translate("MainWindow", "Wrong Team 1"))
        self.CorrectTeam1Button.setText(_translate("MainWindow", "Correct Team 1"))
        self.label.setText(_translate("MainWindow", "Points Go to:"))
        self.DisplayAnswerButton.setText(_translate("MainWindow", "Display Answer"))
        self.label_2.setText(_translate("MainWindow", "GameBoard"))
        self.RoundLabel.setText(_translate("MainWindow", "Round:"))
        self.RoundNumber.setText(_translate("MainWindow", "1"))
        self.resetButton.setText(_translate("MainWindow", "Reset GameBoard"))
        self.nextRoundButton.setText(_translate("MainWindow", "Next Round"))
    
    def cat_click(self, question_num, button): # Clicking clues
        self.RevealedAnswerLabel.setText("Answer") # Resets Answer Label
        #self.RevealedAnswerLabel.adjustSize() # Adjusts Label Size
        self.RevealedQuestionLabel.setText(questions[question_num]['Question']) # Reveals question on click
        self.jeopardy.updateAll(questions[question_num]['Question'], questions[question_num]['Answer'], questions[question_num]['Points'], questions[question_num]['Category'])
        #self.RevealedQuestionLabel.adjustSize()

        button.hide()

        print(self.jeopardy.getQuestion())
        print(self.jeopardy.getAnswer())
        print(self.jeopardy.getCategory())
        print(self.jeopardy.getCurrPoints())

    def display_answer_click(self): # Clicking Display Answer
        answer = self.jeopardy.getAnswer()
        self.RevealedAnswerLabel.setText(str(answer))
        self.RevealedAnswerLabel.adjustSize()

    """Methods for Increasing Points after Correct Answer"""
    def correctTeam1(self):
        self.jeopardy.addTeam1Points()
        self.Team1Score.setText(str(self.jeopardy.getTeam1Score()))
        self.Team1Score.adjustSize()

    def correctTeam2(self):
        self.jeopardy.addTeam2Points()
        self.Team2Score.setText(str(self.jeopardy.getTeam2Score()))
        self.Team2Score.adjustSize()

    def correctTeam3(self):
        self.jeopardy.addTeam3Points()
        self.Team3Score.setText(str(self.jeopardy.getTeam3Score()))
        self.Team3Score.adjustSize()

    def correctTeam4(self):
        self.jeopardy.addTeam4Points()
        self.Team4Score.setText(str(self.jeopardy.getTeam4Score()))
        self.Team4Score.adjustSize()

    """Methods for Decreasing Points after Wrong Answer"""

    def wrongTeam1(self):
        self.jeopardy.subtractTeam1Points()
        self.Team1Score.setText(str(self.jeopardy.getTeam1Score()))
        self.Team1Score.adjustSize()

    def wrongTeam2(self):
        self.jeopardy.subtractTeam2Points()
        self.Team2Score.setText(str(self.jeopardy.getTeam2Score()))
        self.Team2Score.adjustSize()

    def wrongTeam3(self):
        self.jeopardy.subtractTeam3Points()
        self.Team3Score.setText(str(self.jeopardy.getTeam3Score()))
        self.Team3Score.adjustSize()

    def wrongTeam4(self):
        self.jeopardy.subtractTeam4Points()
        self.Team4Score.setText(str(self.jeopardy.getTeam4Score()))
        self.Team4Score.adjustSize()

    """Method for updating labels after gameboard reset"""
    def updateAll(self):
        self.Team1Score.setText(str(self.jeopardy.getTeam1Score()))
        self.Team2Score.setText(str(self.jeopardy.getTeam2Score()))
        self.Team3Score.setText(str(self.jeopardy.getTeam3Score()))
        self.Team4Score.setText(str(self.jeopardy.getTeam4Score()))
        self.RoundNumber.setText(str(self.jeopardy.getRound()))

        self.RevealedQuestionLabel.setText("Question")

        self.RevealedAnswerLabel.setText("Answer")

    """Methods for next round and gameboard reset"""
    def resetGameboard(self):
        self.cat1_clue1.setHidden(False)
        self.cat1_clue2.setHidden(False)
        self.cat1_clue3.setHidden(False)
        self.cat1_clue4.setHidden(False)

        self.cat2_clue1.setHidden(False)
        self.cat2_clue2.setHidden(False)
        self.cat2_clue3.setHidden(False)
        self.cat2_clue4.setHidden(False)

        self.cat3_clue1.setHidden(False)
        self.cat3_clue2.setHidden(False)
        self.cat3_clue3.setHidden(False)
        self.cat3_clue4.setHidden(False)

        self.cat4_clue1.setHidden(False)
        self.cat4_clue2.setHidden(False)
        self.cat4_clue3.setHidden(False)
        self.cat4_clue4.setHidden(False)

        self.cat5_clue1.setHidden(False)
        self.cat5_clue2.setHidden(False)
        self.cat5_clue3.setHidden(False)
        self.cat5_clue4.setHidden(False)

        self.jeopardy.resetScore()
        self.updateAll()

    def nextRound(self):
        global questions

        self.cat1_clue1.setHidden(False)
        self.cat1_clue2.setHidden(False)
        self.cat1_clue3.setHidden(False)
        self.cat1_clue4.setHidden(False)

        self.cat2_clue1.setHidden(False)
        self.cat2_clue2.setHidden(False)
        self.cat2_clue3.setHidden(False)
        self.cat2_clue4.setHidden(False)

        self.cat3_clue1.setHidden(False)
        self.cat3_clue2.setHidden(False)
        self.cat3_clue3.setHidden(False)
        self.cat3_clue4.setHidden(False)

        self.cat4_clue1.setHidden(False)
        self.cat4_clue2.setHidden(False)
        self.cat4_clue3.setHidden(False)
        self.cat4_clue4.setHidden(False)

        self.cat5_clue1.setHidden(False)
        self.cat5_clue2.setHidden(False)
        self.cat5_clue3.setHidden(False)
        self.cat5_clue4.setHidden(False)

        self.jeopardy.increaseRound()
        self.RoundNumber.setText(str(self.jeopardy.getRound()))
        self.RoundNumber.adjustSize()
        self.RevealedQuestionLabel.setText("Question")
        self.RevealedAnswerLabel.setText("Answer")
        with open("JeopardyFinal2.json") as file:
            new_questions = json.load(file)
            questions = new_questions

        self.cat1.setText(questions[0]['Category'])
        self.cat2.setText(questions[4]['Category'])
        self.cat3.setText(questions[8]['Category'])
        self.cat4.setText(questions[12]['Category'])
        self.cat5.setText(questions[16]['Category'])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QtGui.QFontDatabase.addApplicationFont('home/flyseddy/Coding/BTPJeopardy/Fonts/jeopardy/gyparody.ttf')
    style = """
        QWidget{
            background: #D3D3D3;
        }
        QPushButton{
            color: #FFCC00;
            background: #060CE9;
            font-family: "gyparody";
            font-size: 20px;
            font-weight: bold;
        }
        QPushButton#DisplayAnswerButton{
            font-size:15px;
        }
        QLabel{
            font-family: "gyparody";
            font-weight: bold;
        }
        QLabel#RevealedQuestionLabel, QLabel#RevealedAnswerLabel{
            color: #FFFFFF;
            background: #060CE9; 
            font-family: "Arial";
            font-size: 17px;
            font-weight: bold;
        }
        QLabel#seanName{
            font-size:21px;
            font-weight: bold;
        }
        QLabel#BTPLogo{
            color: #FFCC00;
            background:#060CE9; 
            font-family: "gyparody";
            font-size: 40px;
            border-radius: 8px;
            padding:2px;
        }
    """
    app.setStyleSheet(style)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
